"use client";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./navbar";
import "./globals.css";
import { usePathname } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
const disableNavbar = ["/Login","/Register"]

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  return (
    <html lang="en">
      <body className={inter.className}>
      {!disableNavbar.includes(pathname) && <Navbar/>}
        {children}
      </body>
    </html>
  );
}
